name: GitHub Classroom Workflow

on:
  - push
  - workflow_dispatch

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Autograding

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
      name: Autograding
      runs-on: windows-latest
      if: github.actor != 'github-classroom[bot]'
      steps:
      - name: Clone Project
        uses: actions/checkout@v4.1.1
      - name: Configure Visual Studio / MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          msbuild-architecture: x64
      - name: Compile
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      - name: Run Autograding
        uses: education/autograding@v1